baseURL = "https://cilindir.ca/"
languageCode = "en-ca"
title = "Cilindir"
theme = "hugo-theme-lean-launch-page"
author = "Michael Luciuk"
canonifyurls = true

[params]
  mailchimpURL = "https://cilindir.us17.list-manage.com/subscribe/post?u=775074a4e48299ffc7184b09f&amp;id=ee7095d424&amp;f_id=00d6c2e1f0"

[markup]
  [markup.goldmark.renderer]
    unsafe = true